spring.application.name=course-service

server.port=8082
server.servlet.context-path=/


spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/student_analytics_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000

eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.open-in-view=false
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}

# Naming Strategies (Keeps table names consistent)
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
spring.jpa.hibernate.naming.implicit-strategy=org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
hybrid.nlp.url=${NLP_SERVICE_URL:http://hybrid-nlp-service:5001}
cors.allowed-origins=http://localhost:3000,http://localhost:8080,http://localhost:8082,http://localhost:8083,http://localhost:8084,http://localhost:8085

logging.level.com.example.course_service=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG

logging.file.name=logs/course-service.log
logging.file.max-size=10MB
logging.file.max-history=30


spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=UTC
spring.jackson.default-property-inclusion=non_null
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

server.error.include-message=always
server.error.include-binding-errors=always

management.endpoints.web.exposure.include=prometheus,health,info
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.metrics.tags.application=course-service