server.port=8087
server.servlet.context-path=/

spring.application.name=exam-result-service

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/student_analytics_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}
ai.evaluation.url=${AI_EVALUATION_URL:http://ai-integration-service:8084/api/v1/exams/evaluate}

#spring.jackson.serialization.write-dates-as-timestamps=fals
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=UTC

eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost

server.error.include-message=always
server.error.include-binding-errors=always

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB


management.endpoints.web.exposure.include=prometheus,health,info
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.metrics.tags.application=exam-result-service