spring.application.name=ai-integration-service

# ==========================================
# 1. SERVER CONFIGURATION
# ==========================================
server.port=8084

# ==========================================
# 2. DATABASE CONFIGURATION (MySQL)
# ==========================================
# Replace 'student_analytics_db' with your actual database name
# Replace 'root' with your actual MySQL username and password
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/student_analytics_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# ==========================================
# 3. JPA / HIBERNATE CONFIGURATION
# ==========================================
# 'update' automatically creates/updates database tables based on your Java Entities
spring.jpa.hibernate.ddl-auto=update

# Database dialect so Hibernate knows exactly how to write SQL for MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}

# Logging (Crucial for debugging in Final Year Projects)
# Prints the SQL queries in your console so you can see what is happening
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#  mkknkkkkjkjjjfe
nlp.service.url=${NLP_SERVICE_URL:http://hybrid-nlp-service:5001}
performance.service.url=${PERFORMANCE_SERVICE_URL:http://performance-service:8085}

eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

# ==========================================
# 4. MICROSERVICE URLS (Custom Properties)
# ==========================================
# Never hardcode URLs in Java classes. Keep them here so they are easy to change!
#python.ai.service.generate-quiz.url=http://localhost:5001/generate-quiz

management.endpoints.web.exposure.include=prometheus,health,info
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.metrics.tags.application=ai-integration-service